name: Build Client Packages and publish to NPM

on:
  push:
    branches:
      - 'master'
  workflow_dispatch: { }

jobs:
  schemas:
    name: Build Schema Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
      - uses: actions-rs/cargo@v1
        with:
          args: -p audiocloud-api --example export_schemas
          command: run
      - uses: actions-rs/cargo@v1
        with:
          args: -p audiocloud-models --example export_schema
          command: run
      - uses: actions/upload-artifact@v3
        name: Upload files
        with:
          name: schemas
          path: openapi_*.json
  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: schemas
    strategy:
      matrix:
        package:
          - { dir: cloud-client, schema: openapi_cloud.json }
          - { dir: domain-client, schema: openapi_domain.json }
          - { dir: audio-engine-client, schema: openapi_audio_engine.json }
          - { dir: instance-driver-client, schema: openapi_instance_driver.json }
          - { dir: models, schema: openapi_models.json }
    steps:
      - uses: actions/checkout@v2
        name: Checkout API code
      - name: Download binary artifact
        uses: actions/download-artifact@v3
        with:
          name: schemas
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: |
          cp ../../${{ matrix.package.schema }} .
          npm ci
          npm run generate
          npx tsc
        name: Install deps, generate and build client
        working-directory: './packages/${{ matrix.package.dir }}'
      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PACKAGEJSON_DIR: './packages/${{ matrix.package.dir }}'
#      - run: npm publish --access public
#        name: Publish to NPM
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
#        working-directory: ./packages/${{ matrix.package.dir }}
